"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {SettlementStatus,assertTransition}=require("../src/settlement/model");
const {StripeTransferService}=require("../src/settlement/stripeTransferService");
const {createStripeWebhookHandler}=require("../src/webhooks/stripeWebhookHandler");
const {ReconciliationService}=require("../src/settlement/reconciliationService");

test("terminal settlement cannot transition",()=>assert.throws(()=>assertTransition(SettlementStatus.SUCCEEDED,SettlementStatus.CLAIMED),/Illegal/));
test("Stripe adapter forwards deterministic key",async()=>{let seen;const stripe={transfers:{create:async(a,o)=>{seen=o.idempotencyKey;return{id:"tr_test"};}}};const s=new StripeTransferService({stripe});const r=await s.createTransfer({amount:100,currency:"usd",destination:"acct_test",metadata:{}},{idempotencyKey:"stable"});assert.equal(r.kind,"succeeded");assert.equal(seen,"stable");});
test("Stripe timeout becomes unknown",async()=>{const stripe={transfers:{create:async()=>{throw{type:"StripeConnectionError"};}}};const r=await new StripeTransferService({stripe}).createTransfer({amount:100,currency:"usd",destination:"acct_test",metadata:{}},{idempotencyKey:"stable"});assert.equal(r.kind,"unknown");});
test("webhook replay is suppressed",async()=>{let claims=0,handled=0;const stripe={webhooks:{constructEvent:()=>({id:"evt_1",type:"payment_intent.succeeded",data:{object:{}},livemode:false})}};const eventRepository={claim:async()=>++claims===1?{kind:"acquired",record:{status:"processing"}}:{kind:"duplicate",record:{status:"processed",result:"ok"}},complete:async()=>{},fail:async()=>{}};const reconciler={handle:async()=>{handled++;return{kind:"ok"};}};const h=createStripeWebhookHandler({stripe,webhookSecret:"test",eventRepository,reconciler,logger:{info(){}}});await h({rawBody:Buffer.from("x"),signature:"test"});const r=await h({rawBody:Buffer.from("x"),signature:"test"});assert.equal(r.duplicate,true);assert.equal(r.result,"ok");assert.equal(handled,1);});
test("invalid webhook signature is rejected before persistence",async()=>{let claimed=false;const stripe={webhooks:{constructEvent:()=>{throw new Error("bad signature");}}};const eventRepository={claim:async()=>{claimed=true;}};const h=createStripeWebhookHandler({stripe,webhookSecret:"test",eventRepository,reconciler:{},logger:{info(){}}});await assert.rejects(()=>h({rawBody:Buffer.from("x"),signature:"bad"}),/signature/);assert.equal(claimed,false);});
test("reconciler repairs transfer found by settlement identity",async()=>{let confirmed=false;const repository={get:async()=>({identity:"i",status:"processing",jobId:"j",paymentId:"p",attemptId:"a"}),loadEligibleObligation:async()=>({paymentStatus:"succeeded"}),confirm:async()=>{confirmed=true;}};const stripe={findTransferBySettlementIdentity:async()=>({id:"tr_test"})};const r=await new ReconciliationService({repository,stripe}).reconcile("i");assert.equal(r.kind,"reconciledSuccess");assert.equal(confirmed,true);});
test("failed payment webhook classifies settlement as blocked",async()=>{const r=await new ReconciliationService({repository:{},stripe:{}}).handle("payment_intent.payment_failed",{});assert.equal(r.kind,"blocked");});
test("restricted Connect account requires manual review",async()=>{const r=await new ReconciliationService({repository:{},stripe:{}}).handle("account.updated",{charges_enabled:false,payouts_enabled:false});assert.equal(r.kind,"manualReview");});
