"use strict";
const test=require("node:test"); const assert=require("node:assert/strict");
const admin=require("firebase-admin");
const {initializeTestEnvironment,assertFails}=require("@firebase/rules-unit-testing");
const {FirestoreSettlementRepository}=require("../src/settlement/firestoreSettlementRepository");
const {createCompletionHandler}=require("../src/settlement/completionHandler");
const {validateEligibility}=require("../src/settlement/settlementService");
const {FirestoreStripeEventRepository}=require("../src/webhooks/firestoreStripeEventRepository");

const projectId="oddjobs-gate5-test"; let env,v2env,db,repo,seq=0;
test.before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:"127.0.0.1",port:8080,rules:require("fs").readFileSync("../firestore.emergency.rules","utf8")}});v2env=await initializeTestEnvironment({projectId:"oddjobs-gate5-v2-test",firestore:{host:"127.0.0.1",port:8080,rules:require("fs").readFileSync("../firestore.v2.rules","utf8")}});admin.initializeApp({projectId});db=admin.firestore();repo=new FirestoreSettlementRepository({db});});
test.beforeEach(async()=>{await env.clearFirestore();await v2env.clearFirestore();}); test.after(async()=>{await env.cleanup();await v2env.cleanup();await admin.app().delete();});
function ids(){seq++;return {jobId:`job${seq}`,paymentId:`payment${seq}`,identity:`job${seq}:payment${seq}:v1`};}
async function seed(overrides={}){const x=ids();const job={progressStatus:"completed",assignedWorkerID:"worker1",paymentId:x.paymentId,...overrides.job};const payment={jobId:x.jobId,status:"succeeded",recipientId:"worker1",workerAmount:4750,currency:"usd",destinationAccountId:"acct_test",paymentIntentId:"pi_test",...overrides.payment};await db.collection("jobPost").doc(x.jobId).set(job);if(!overrides.missingPayment)await db.collection("payments").doc(x.paymentId).set(payment);return {...x,job,payment};}
function snap(id,data,exists=true){return {id,exists,data:()=>data};}
async function pending(x){return repo.createPendingFromCompletion({identity:x.identity,version:1,jobId:x.jobId,paymentId:x.paymentId});}

test("1 completion creates one pending settlement",async()=>{const x=await seed();const h=createCompletionHandler({repository:repo,logger:{info(){},warn(){}}});const r=await h(snap(x.jobId,{progressStatus:"active"}),snap(x.jobId,x.job));assert.equal(r.kind,"pending");assert.equal((await repo.get(x.identity)).status,"pending");});
test("2 duplicate completion event creates one obligation",async()=>{const x=await seed();await Promise.all([pending(x),pending(x)]);const q=await db.collection("settlements").get();assert.equal(q.size,1);});
test("3 repeated completed update is ignored",async()=>{const x=await seed();const h=createCompletionHandler({repository:repo,logger:{info(){},warn(){}}});const r=await h(snap(x.jobId,x.job),snap(x.jobId,{...x.job,title:"changed"}));assert.equal(r.kind,"ignored");assert.equal((await db.collection("settlements").get()).size,0);});
test("4 concurrent leases have one winner",async()=>{const x=await seed();await pending(x);const now=new Date();const r=await Promise.all([repo.claim({identity:x.identity,owner:"a",attemptId:"a",now,leaseMs:60000}),repo.claim({identity:x.identity,owner:"b",attemptId:"b",now,leaseMs:60000})]);assert.equal(r.filter(v=>v.kind==="acquired").length,1);assert.equal(r.filter(v=>v.kind==="busy").length,1);});
test("5 expired lease can be reclaimed",async()=>{const x=await seed();await pending(x);await repo.claim({identity:x.identity,owner:"a",attemptId:"a",now:new Date(0),leaseMs:1});const r=await repo.claim({identity:x.identity,owner:"b",attemptId:"b",now:new Date(),leaseMs:60000});assert.equal(r.kind,"acquired");});
test("6 active lease cannot be stolen",async()=>{const x=await seed();await pending(x);const now=new Date();await repo.claim({identity:x.identity,owner:"a",attemptId:"a",now,leaseMs:60000});const r=await repo.claim({identity:x.identity,owner:"b",attemptId:"b",now,leaseMs:60000});assert.equal(r.kind,"busy");});
test("7 unauthorized client cannot mutate settlement",async()=>{const c=env.authenticatedContext("user1").firestore();await assertFails(c.collection("settlements").doc("x").set({status:"succeeded"}));});
function eligible(over={}){return {jobId:"j",paymentId:"p",jobPaymentId:"p",paymentJobId:"j",jobStatus:"completed",paymentStatus:"succeeded",workerId:"w",paymentRecipientId:"w",workerAmount:100,currency:"usd",destinationAccountId:"acct_x",cancelled:false,refunded:false,disputed:false,priorSettlement:false,...over};}
test("8 cancelled job cannot settle",()=>assert.throws(()=>validateEligibility(eligible({cancelled:true})),/blocked/));
test("9 refunded job cannot settle",()=>assert.throws(()=>validateEligibility(eligible({refunded:true})),/blocked/));
test("10 disputed job cannot settle",()=>assert.throws(()=>validateEligibility(eligible({disputed:true})),/blocked/));
test("11 wrong worker cannot settle",()=>assert.throws(()=>validateEligibility(eligible({paymentRecipientId:"x"})),/mismatch/));
test("12 wrong destination cannot settle",()=>assert.throws(()=>validateEligibility(eligible({destinationAccountId:null})),/blocked/));
test("13 wrong amount cannot settle",()=>assert.throws(()=>validateEligibility(eligible({workerAmount:-1})),/amount/));
test("14 missing payment cannot create obligation",async()=>{const x=await seed({missingPayment:true});const r=await pending(x);assert.equal(r.kind,"manualReview");});
test("15 failed payment cannot settle",()=>assert.throws(()=>validateEligibility(eligible({paymentStatus:"failed"})),/eligible/));
test("16 succeeded payment is eligible",()=>assert.doesNotThrow(()=>validateEligibility(eligible())));
test("17 expired processing lease after crash is recoverable",async()=>{const x=await seed();await pending(x);await repo.claim({identity:x.identity,owner:"a",attemptId:"a",now:new Date(0),leaseMs:1});await repo.recordAttempt({identity:x.identity,attemptId:"a",idempotencyKeyDigest:"digest",now:new Date(0)});const r=await repo.claim({identity:x.identity,owner:"b",attemptId:"b",now:new Date(),leaseMs:60000});assert.equal(r.kind,"acquired");});
function eventMeta(overrides={}){return {type:"payment_intent.succeeded",created:123,apiVersion:"2025-01-01",livemode:false,handlerVersion:"gate5.5-test",...overrides};}
test("18 Stripe event metadata is durable and minimal",async()=>{const now=new Date("2026-01-01T00:00:00Z");const events=new FirestoreStripeEventRepository({db,clock:()=>now});const r=await events.claim("evt_durable",eventMeta());assert.equal(r.kind,"acquired");const d=(await db.collection("stripeEvents").doc("evt_durable").get()).data();assert.equal(d.eventId,"evt_durable");assert.equal(d.status,"processing");assert.equal(d.attemptCount,1);assert.equal(d.handlerVersion,"gate5.5-test");assert.equal(Object.hasOwn(d,"rawBody"),false);});
test("19 processed Stripe event returns previous result",async()=>{const events=new FirestoreStripeEventRepository({db});await events.claim("evt_complete",eventMeta());await events.complete("evt_complete",{status:"processed",result:"reconciledSuccess"});const r=await events.claim("evt_complete",eventMeta());assert.equal(r.kind,"duplicate");assert.equal(r.record.result,"reconciledSuccess");assert.equal(r.record.attemptCount,1);});
test("20 active Stripe event processing lease cannot be stolen",async()=>{const now=new Date();const events=new FirestoreStripeEventRepository({db,clock:()=>now,leaseMs:60000});await events.claim("evt_busy",eventMeta());const r=await events.claim("evt_busy",eventMeta());assert.equal(r.kind,"busy");assert.equal(r.record.attemptCount,1);});
test("21 expired Stripe event processing resumes after crash",async()=>{let now=new Date(0);const events=new FirestoreStripeEventRepository({db,clock:()=>now,leaseMs:1});await events.claim("evt_resume",eventMeta());now=new Date(100);const r=await events.claim("evt_resume",eventMeta());assert.equal(r.kind,"acquired");assert.equal(r.record.attemptCount,2);});
test("22 failed Stripe event requires deliberate retry",async()=>{const events=new FirestoreStripeEventRepository({db});await events.claim("evt_failed",eventMeta());await events.fail("evt_failed",{code:"provider_timeout"});const suppressed=await events.claim("evt_failed",eventMeta());assert.equal(suppressed.kind,"duplicate");const retry=await events.claim("evt_failed",eventMeta(),{retryFailed:true});assert.equal(retry.kind,"acquired");assert.equal(retry.record.attemptCount,2);});
test("23 unauthorized client cannot mutate Stripe event state",async()=>{const c=env.authenticatedContext("user1").firestore();await assertFails(c.collection("stripeEvents").doc("evt_client").set({status:"processed"}));});
async function seedV2(path,data){await v2env.withSecurityRulesDisabled(async c=>c.firestore().doc(path).set(data));return v2env.authenticatedContext("user1").firestore().doc(path);}
test("24 V2 client cannot modify payment settlement outcome",async()=>{const ref=await seedV2("payments/p1",{senderId:"user1",recipientId:"user2",payoutStatus:"pending"});await assertFails(ref.update({payoutStatus:"paid",stripeTransferId:"tr_fake"}));});
test("25 V2 client cannot modify withdrawal outcome",async()=>{const ref=await seedV2("withdraws/w1",{userId:"user1",status:"requested"});await assertFails(ref.update({status:"paid"}));});
test("26 V2 client cannot modify balance authority",async()=>{const ref=await seedV2("balance/user1",{totalEarned:0});await assertFails(ref.update({totalEarned:999999}));});
